Disable test on Python 3
It breaks the testsuite somehow:

  Tear down zodbbrowser.ftests.test_standalone.TestsWithServer Traceback (most recent call last):
  File "/home/mg/src/zodbbrowser/.tox/py36/bin/zope-testrunner", line 11, in <module>
    sys.exit(run())
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zope/testrunner/__init__.py", line 31, in run
    warnings=warnings)
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zope/testrunner/__init__.py", line 51, in run_internal
    runner.run()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zope/testrunner/runner.py", line 189, in run
    self.run_tests()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zope/testrunner/runner.py", line 291, in run_tests
    self.skipped, self.import_errors)
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zope/testrunner/runner.py", line 443, in run_layer
    tear_down_unneeded(options, needed, setup_layers)
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zope/testrunner/runner.py", line 742, in tear_down_unneeded
    l.tearDown()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zodbbrowser/ftests/test_standalone.py", line 145, in tearDown
    cls.server.stop()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zodbbrowser/ftests/test_standalone.py", line 106, in stop
    stop_serving()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zodbbrowser/standalone.py", line 154, in stop_serving
    getUtility(IDatabase, '<target>').close()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/ZODB/DB.py", line 659, in close
    self._mvcc_storage.close()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/ZODB/mvccadapter.py", line 68, in close
    self._storage.close()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/ZODB/FileStorage/FileStorage.py", line 507, in close
    self._lock_file.close()
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zc/lockfile/__init__.py", line 114, in close
    _unlock_file(self._fp)
  File "/home/mg/src/zodbbrowser/.tox/py36/lib/python3.6/site-packages/zc/lockfile/__init__.py", line 62, in _unlock_file
    fcntl.flock(file.fileno(), fcntl.LOCK_UN)
OSError: [Errno 9] Bad file descriptor